version: '3.1'
services:
  jaegertracing:
    image: jaegertracing/all-in-one:1.43
    scale: 1
    container_name: jaegertracing
    ports:
      - "16686:16686"
      - "16685:16685"
      - "14268:14268"
      - "14250:14250"
      - "6831:6831/udp"
      - "6832:6832/udp"
  otel-collector:
    image: otel/opentelemetry-collector:0.73.0
    scale: 0
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
    #   - "1888:1888"   # pprof extension
    #   - "13133:13133" # health_check extension
      - "4317:4317"        # OTLP gRPC receiver
    #   - "4318:4318"        # OTLP HTTP receiver
    #   - "55670:55679" # zpages extension
    depends_on:
      - jaegertracing
      - tempo
  tempo:
    image: grafana/tempo:latest
    scale: 1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo:/tmp/tempo
    ports:
      # - "14268:14268" # jaeger
      - "3200:3200"   # tempo
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
  prometheus:
    image: prom/prometheus:latest
    scale: 1
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:9.4.3
    scale: 1
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
